language: clojure
env:
  - NSQ_DOWNLOAD=nsq-0.2.24.linux-amd64.go1.2
  - NSQ_DOWNLOAD=nsq-0.2.27.linux-amd64.go1.2
  - NSQ_DOWNLOAD=nsq-0.2.28.linux-amd64.go1.2.1
  - NSQ_DOWNLOAD=nsq-0.2.30.linux-amd64.go1.3
  - NSQ_DOWNLOAD=nsq-0.2.31.linux-amd64.go1.3.1
script:
  - wget http://bitly-downloads.s3.amazonaws.com/nsq/$NSQ_DOWNLOAD.tar.gz
  - tar zxvf $NSQ_DOWNLOAD.tar.gz
  - sudo cp $NSQ_DOWNLOAD/bin/nsqd $NSQ_DOWNLOAD/bin/nsqlookupd /usr/local/bin
  - lein test
notifications:
  email: false
